config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"


  post "tasks/create", to: "tasks#create"
  get "tasks/new", to: "tasks#new", as: :new_task
  get "tasks/:id", to: "tasks#show", as: :task
  get "tasks", to: "tasks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @taskShow = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(title: params[:title], details: params[:details])
    if @task.save
      redirect_to tasks_path, notice: "Tarea '#{params[:title]}' creada !"
    else
      render :new, status: :unprocessable_entity
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <div class="container">
    <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tasks/index.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-info">
    <%= msg %>
  </div>
<% end %>

<h1>My Tasks</h1>
<% @tasks.each do |task| %>
<div class="form-check">
  <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault" <%= "checked" if task.completed == true %> />
  <label class="form-check-label" for="flexCheckDefault">
    <%= link_to task.title, task_path(task) %>
  </label>
</div>
<%end%>

<%= link_to "Nueva Tarea", new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>
<form action="create" method = "POST">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <div class="mb-3">
    <input type="text" name="title" class="form-control" placeholder="Nombre de la Tarea">
  </div>
  <div class="mb-3">
    <textarea class="form-control" name="details" rows="3" placeholder="Agregue un detalle a la tarea"></textarea>
  </div>
  <button type="submit" class="btn btn-primary">Agregar</button>
</form>

<%= link_to  "Regresar a la lista", :back %>

app/views/tasks/show.html.erb
<h1><%= @taskShow.title %></h1>

<div class="detailShow">
  <%= @taskShow.details %>
</div>

<div class="form-check">
  <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault" <%= "checked" if @taskShow.completed == true %> >
  <label class="form-check-label" for="flexCheckDefault">
    Marcar como completado
  </label>
</div>
<%= link_to "Regresar a la lista", :back %>